spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutuo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tEijDcL6YSVDCNjapPD
    accessKeySecret: uCDcfe5M3eKHaU7vYSholOUTQE0KdS
    bucketName: 1kunkun1

server:
  ssl:
    key-store: classpath:certificate.jks
    key-store-type: PKCS12
    key-store-password: b58a52
  port: 443

openai:
  apikey: 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
  chatEndpoint: https://api.openai.com/v1/chat/completions

